server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://192.168.1.130:3306/textdb?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    hikari:
      connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5 # 最小连接数
      maximum-pool-size: 20 # 最大连接数
      auto-commit: true # 自动提交
      idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP # 连接池名字
      max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  elasticsearch:
    rest:
      uris: http://192.168.1.130:9200






